-- Queries lifted from Web Intelligence Report: Archive ECUM Report
--
-- Public Folders / TPS Archive Reports / Accountability
--
-- Title:       Archive ECUM Report
-- ID, CUID:    366159, ASmuaqU75d5GjIzhUtscTb0
-- File Name:   frs://Input/a_079/150/005/366159/~ce1e086fc8dc0d050.wid
-- Description: Electronic Cumulative Report from archived Mainframe Student Data. BIRTHDATE/LAST NAME PROMPT.
--

USE ECUM_Report_Student
GO

CREATE SCHEMA ecum_queries
GO

-- Student Data(Tests)
CREATE PROCEDURE ecum_queries.student_data_tests @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_LNAME,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_FNAME,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_MI,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_GRADE,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_CURR_SCH,
  ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_NAME
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.BUILDING_MASTER ON (ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_KEY=ECUM_Report_Student.ECUM.STUDENT.STUDENT_CURR_SCH)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- ADMIN
CREATE PROCEDURE ecum_queries.admin @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- ACT
CREATE PROCEDURE ecum_queries.act @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SSN,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SCORE_ENGLISH,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SCORE_MATH,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SCORE_READING,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SCORE_SCIENCE,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SCORE_COMPOSITE,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.TEST_TYPE,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SUBSCORE_UM,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SUBSCORE_RH,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SUBSCORE_EA,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SUBSCORE_AG,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SUBSCORE_GT,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SUBSCORE_SS,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.SUBSCORE_AL,
  ECUM_Report_Student.ECUM.TESTS_ACTTEST.NAT_SCORE_COMPOSITE
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_ACTTEST ON (ECUM_Report_Student.ECUM.TESTS_ACTTEST.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_ACTTEST.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_ACTTEST.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_ACTTEST.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_ACTTEST.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- EOI
CREATE PROCEDURE ecum_queries.eoi @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_EOI.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_SCORE,
  ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_PERF_LVL,
  ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_PASS_FAIL,
  ECUM_Report_Student.ECUM.TESTS_EOI.HIST_SCORE,
  ECUM_Report_Student.ECUM.TESTS_EOI.HIST_PERF_LVL,
  ECUM_Report_Student.ECUM.TESTS_EOI.HIST_PASS_FAIL,
  ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_SCORE,
  ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_PERF_LVL,
  ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_PASS_FAIL,
  ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_SCORE,
  ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_PERF_LVL,
  ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_PASS_FAIL,
  CASE WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_PERF_LVL = 'A' 	  THEN 'Advanced'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_PERF_LVL = 'L' THEN 'Limited Knowledge'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_PERF_LVL = 'S' THEN 'Satisfactory'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_PERF_LVL = 'U' THEN 'Unsatisfactory'
	ELSE 'Unkown'
	END,
  CASE WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_PASS_FAIL IN ('P','Y') THEN 'Pass'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ENGL_PASS_FAIL IN ('N','F') THEN 'Fail'
	ELSE '  '
	END,
  CASE WHEN ECUM_Report_Student.ECUM.TESTS_EOI.HIST_PERF_LVL = 'A' 	  THEN 'Advanced'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.HIST_PERF_LVL = 'L' THEN 'Limited Knowledge'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.HIST_PERF_LVL = 'S' THEN 'Satisfactory'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.HIST_PERF_LVL = 'U' THEN 'Unsatisfactory'
	ELSE 'Unkown'
	END,
  CASE WHEN ECUM_Report_Student.ECUM.TESTS_EOI.HIST_PASS_FAIL IN ('P','Y') THEN 'Pass'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.HIST_PASS_FAIL IN ('N','F') THEN 'Fail'
	ELSE '    '
	END,
  CASE WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_PERF_LVL = 'A' 	  THEN 'Advanced'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_PERF_LVL = 'L' THEN 'Limited Knowledge'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_PERF_LVL = 'S' THEN 'Satisfactory'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_PERF_LVL = 'U' THEN 'Unsatisfactory'
	ELSE 'Unkown'
	END,
  CASE WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_PASS_FAIL IN ('P','Y') THEN 'Pass'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.ALGE_PASS_FAIL IN ('N','F') THEN 'Fail'
	ELSE '  '
	END,
  CASE WHEN ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_PERF_LVL = 'A' 	  THEN 'Advanced'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_PERF_LVL = 'L' THEN 'Limited Knowledge'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_PERF_LVL = 'S' THEN 'Satisfactory'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_PERF_LVL = 'U' THEN 'Unsatisfactory'
	ELSE 'Unkown'
	END,
  CASE WHEN ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_PASS_FAIL IN ('P','Y') THEN 'Pass'
	WHEN ECUM_Report_Student.ECUM.TESTS_EOI.BIOL_PASS_FAIL IN ('N','F') THEN 'Fail'
	ELSE '  '
	END
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_EOI ON (ECUM_Report_Student.ECUM.TESTS_EOI.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_EOI.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_EOI.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_EOI.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_EOI.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- Explore
CREATE PROCEDURE ecum_queries.explore @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.ENGLISH_SCR,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.MATH_SCR,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.READING_SCR,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.SCIENCE_SCR,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.COMPOSITE_SCR,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.SUBSCORE_UM,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.SUBSCORE_RH,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.ENGLISH_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.MATH_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.READING_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.SCIENCE_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.COMPOSITE_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.NAT_PERC_UM,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.NAT_PERC_RH,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.ENGLISH_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.MATH_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.READING_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.SCIENCE_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.COMPOSITE_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.LOC_PERC_UM,
  ECUM_Report_Student.ECUM.TESTS_EXPLTEST.LOC_PERC_RH
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_EXPLTEST ON (ECUM_Report_Student.ECUM.TESTS_EXPLTEST.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_EXPLTEST.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_EXPLTEST.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_EXPLTEST.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_EXPLTEST.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- ITBS
CREATE PROCEDURE ecum_queries.itbs @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.MEASURE_RANK,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.LISTENING,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.WORD_ANALYSIS,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.VOCABULARY,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.READING,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.SPELLING,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.CAPITALIZATION,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.PUNCTUATION,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.USAGE_AND_EXPRESSION,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.LANGUAGE_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.VISUAL_MATERIALS,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.REFERENCE_MATERIALS,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.WORK_STUDY_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.MATH_CONCEPTS,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.MATH_PROBLEM_SOLVING,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.MATH_COMPUTATION,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.MATH_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.COMPLETE_COMPOSITE,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.TOTAL_COMPOSITE,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.SOCIAL_STUDIES,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.SCIENCE,
  ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.RIV_READ_SS_NPR_NCE
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM ON (ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_ITBS_CUSTOM.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- NAGL
CREATE PROCEDURE ecum_queries.nagl @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_NAGL.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_AGE_YEARS,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_AGE_MNTHS,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_RAW_SCORE,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_NAI_SCORE,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_NAI_PCT,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_NAI_STANINE,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_GRD_ABILITY,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_GRD_PCT,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_GRD_STANINE,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_SCALE_SCORE,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_ADJ_NAI_SCORE,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_ADJ_NAI_PCT,
  ECUM_Report_Student.ECUM.TESTS_NAGL.NAGL_ADJ_NAI_STANINE
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_NAGL ON (ECUM_Report_Student.ECUM.TESTS_NAGL.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_NAGL.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_NAGL.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_NAGL.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_NAGL.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- NewITBS
CREATE PROCEDURE ecum_queries.newitbs @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.MEASURE_RANK,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.VOCABULARY,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.'READING ADV_SK' as READING_ADV_SK,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.READING_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.LISTENING,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.SPELLING,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.CAPITALIZATION,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.PUNCTUATION,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.LANGUAGE_USAGE_EXPRESSION,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.LANGUAGE_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.MATH_CONCEPTS_ESTIMATION,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.MATH_PROBLEM_SOLVING,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.MATH_COMPUTATION,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.MATH_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.CORE_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.WORD_ANALYSIS,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.SOCIAL_STUDIES,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.SCIENCE,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.MAPS_DIAGRAMS,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.REFERENCE_MATERIALS,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.SOURCE_INFO_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.COMPOSITION,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.MATH_TOTAL_COMPU,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.CORE_TOTAL_COMPU,
  ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.COMPOSITE_COMPU
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM ON (ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_NEWITBS_CUSTOM.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- OCC
CREATE PROCEDURE ecum_queries.occ @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.MATH_TOT_POSS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.MATH_TOT_EARN,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.MATH_PERCENTC,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.MATH_MC_PASS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.MATH_PL,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.MATH_OPI,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.SCIENCE_TOT_POSS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.SCIENCE_TOT_EARN,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.SCIENCE_PERCENTC,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.SCIENCE_MC_PASS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.SCIENCE_PL,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.SCIENCE_OPI,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.READ_TOT_POSS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.READ_TOT_EARN,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.READ_PERCENTC,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.READ_MC_PASS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.READ_PL,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.READ_OPI,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.USHIST_TOT_POSS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.USHIST_TOT_EARN,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.USHIST_PERCENTC,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.USHIST_MC_PASS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.USHIST_PL,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.USHIST_OPI,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.GEOGRAPHY_TOT_POSS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.GEOGRAPHY_TOT_EARN,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.GEOGRAPHY_PERCENTC,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.GEOGRAPHY_MC_PASS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.GEOGRAPHY_PL,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.GEOGRAPHY_OPI,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.OKHIST_TOT_POSS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.OKHIST_TOT_EARN,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.OKHIST_PERCENTC,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.OKHIST_MC_PASS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.OKHIST_PL,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.OKHIST_OPI,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.ARTS_TOT_POSS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.ARTS_TOT_EARN,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.ARTS_PERCENTC,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.ARTS_MC_PASS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.ARTS_PL,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.ARTS_OPI,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.WRI_EARN,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.WRI_PASS,
  ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.WRI_PL
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM ON (ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_OCC_CUSTOM.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- OTIS
CREATE PROCEDURE ecum_queries.otis @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_OTIS.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_AGE_YEARS,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_AGE_MNTHS,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_RAW_SCORE,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_SAI_SCORE,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_SAI_PCT,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_SAI_STANINE,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_GRD_ABILITY,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_GRD_PCT,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_GRD_STANINE,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_SCALE_SCORE,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_ADJ_SAI_SCORE,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_ADJ_SAI_PCT,
  ECUM_Report_Student.ECUM.TESTS_OTIS.OTIS_ADJ_SAI_STANINE
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_OTIS ON (ECUM_Report_Student.ECUM.TESTS_OTIS.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_OTIS.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_OTIS.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_OTIS.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_OTIS.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- PBP
CREATE PROCEDURE ecum_queries.pbp @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_PBP.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS1,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT1,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS2,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT2,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS3,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT3,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS4,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT4,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS5,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT5,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS6,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT6,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS7,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT7,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS8,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT8,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS9,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT9,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS10,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT10,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS11,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT11,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS12,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT12,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS13,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT13,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS14,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT14,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS15,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT15,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS16,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT16,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS17,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT17,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS18,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT18,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS19,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT19,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS20,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT20,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS21,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT21,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS22,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT22,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS23,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT23,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS24,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT24,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS25,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT25,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS26,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT26,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_RS27,
  ECUM_Report_Student.ECUM.TESTS_PBP.PBP_PCT27
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_PBP ON (ECUM_Report_Student.ECUM.TESTS_PBP.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_PBP.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_PBP.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_PBP.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_PBP.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- Plan
CREATE PROCEDURE ecum_queries.plan_test @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.ENGLISH_SCR,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.MATH_SCR,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.READING_SCR,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.SCIENCE_SCR,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.COMPOSITE_SCR,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.SUBSCORE_USE,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.SUBSCORE_RHET,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.SUBSCORE_ALG,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.SUBSCORE_GEO,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.ENGLISH_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.MATH_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.READING_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.SCIENCE_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.COMPOSITE_NAT_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.NAT_PERC_UM,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.NAT_PERC_RS,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.NAT_PERC_ALG,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.NAT_PERC_GEO,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.ENGLISH_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.MATH_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.READING_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.SCIENCE_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.COMPOSITE_LOC_PERC,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.LOC_PERC_UM,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.LOC_PERC_RS,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.LOC_PERC_ALG,
  ECUM_Report_Student.ECUM.TESTS_PLANTEST.LOC_PERC_GEO
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_PLANTEST ON (ECUM_Report_Student.ECUM.TESTS_PLANTEST.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_PLANTEST.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_PLANTEST.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_PLANTEST.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_PLANTEST.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- Reading
CREATE PROCEDURE ecum_queries.reading @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  Alias_ECUM_BUILDING_MASTER.BLDG_NAME,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.RAW_SCORE_1,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.PERCENTILE_1,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.GE_1,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.RAW_SCORE_2,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.PERCENTILE_2,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.GE_2,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.RAW_SCORE_3,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.PERCENTILE_3,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.GE_3,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.RAW_SCORE_4,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.PERCENTILE_4,
  ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.GE_4
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM ON (ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.BUILDING_MASTER  Alias_ECUM_BUILDING_MASTER ON (Alias_ECUM_BUILDING_MASTER.BLDG_KEY=ECUM_Report_Student.ECUM.TESTS_READING_CUSTOM.SCHOOL)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- SAT
CREATE PROCEDURE ecum_queries.sat @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_SATCOLL.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_SATCOLL.VERBAL_SCORE,
  ECUM_Report_Student.ECUM.TESTS_SATCOLL.MATH_SCORE,
  ECUM_Report_Student.ECUM.TESTS_SATCOLL.VERBAL_PERCENT,
  ECUM_Report_Student.ECUM.TESTS_SATCOLL.MATH_PERCENT
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_SATCOLL ON (ECUM_Report_Student.ECUM.TESTS_SATCOLL.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_SATCOLL.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_SATCOLL.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_SATCOLL.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_SATCOLL.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- SAT9
CREATE PROCEDURE ecum_queries.sat9 @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_DATE,
  ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SORT_GRADE,
  ECUM_Report_Student.ECUM.TESTS_TEST.TEST_NAME,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.SCHOOL_NAME,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.MEASURE_RANK,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.READING_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.WORD_STUDY,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.READING_VOCABULARY,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.READING_COMPREH,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.TOTAL_MATH,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.PROBLEM_SOLVING,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.PROCEDURES,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.NOT_ACTIVE,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.LANGUAGE_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.LANGUAGE_MECH,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.LANGUAGE_EXP,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.SPELLING,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.STUDY_SKILLS,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.ENVIRONMENT,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.SCIENCE,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.SOCIAL_SCIENCE,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.LISTENING,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.USING_INFO,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.THINKING_SKILLS,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.PARTIAL_BATTERY,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.COMPLETE_BATTERY,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.THREE_R_TOTAL,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.USING_INFO_BB,
  ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.THINKING_SKILLS_BB
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.TESTS_ADMINISTERED ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM ON (ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.STUDENT_NUMBER=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.STUDENT_NUMBER and ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.SEQ_NUM=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.SEQ_NUM and ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.TYPE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE and ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.DATE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.DATE and ECUM_Report_Student.ECUM.TESTS_SAT9_CUSTOM.GRADE=ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.GRADE)
   INNER JOIN ECUM_Report_Student.ECUM.TESTS_TEST ON (ECUM_Report_Student.ECUM.TESTS_ADMINISTERED.TYPE=ECUM_Report_Student.ECUM.TESTS_TEST.TEST_TYPE)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- Student Data(Transcript)
CREATE PROCEDURE ecum_queries.student_data_transcript @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER,
  Convert(CHAR(10),( ECUM_Report_Student.ECUM.STUDENT.STUDENT_SSN )) STUDENT_SSN,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_LNAME,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_FNAME,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_MI,
  ECUM_Report_Student.ECUM.STUDENT.GOESBYNAME,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_BIRTHDATE,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_SEX,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_RACE,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_GRADE,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_HOUSE_NO,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_DIRECTION,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_STREET,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_APT_NO,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_ZIP1,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_PHONE,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_ENTRY_DATE,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_CURR_SCH
FROM
  ECUM_Report_Student.ECUM.STUDENT
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- ADDHIST
CREATE PROCEDURE ecum_queries.addhist @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.ADDR_DATE,
  ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.HOUSE_NUMBER,
  ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.DIRECTION,
  ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.STREET_NAME,
  ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.APARTMENT_LOT_NO,
  ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.BLDG_LOT_NO,
  ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.ZIP_CODE,
  ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.ZIP_SUFFIX
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.ADDHIST_CICSTST1 ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.ADDHIST_CICSTST1.STUDENT_NUMBER)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- ATTEND
CREATE PROCEDURE ecum_queries.attend @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.ATTEND_CUSTOM.ATTENDANCE_YEAR,
  SUM(ECUM_Report_Student.ECUM.ATTEND_CUSTOM.DAYS_PRESENT) SUM_DAYS_PRESENT,
  SUM(ECUM_Report_Student.ECUM.ATTEND_CUSTOM.DAYS_ABSENT) SUM_DAYS_ABSENT,
  SUM(ECUM_Report_Student.ECUM.ATTEND_CUSTOM.DAYS_NON_MEMBER) SUM_DAYS_NON_MEMBER,
  ECUM_Report_Student.ECUM.ATTEND_CUSTOM.SCHOOL,
  ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_NAME
FROM
  ECUM_Report_Student.ECUM.BUILDING_MASTER INNER JOIN ECUM_Report_Student.ECUM.ATTEND_CUSTOM ON (ECUM_Report_Student.ECUM.ATTEND_CUSTOM.SCHOOL=ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_KEY)
   INNER JOIN ECUM_Report_Student.ECUM.STUDENT ON (ECUM_Report_Student.ECUM.ATTEND_CUSTOM.STUDENT_NUMBER=ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GROUP BY
  ECUM_Report_Student.ECUM.ATTEND_CUSTOM.ATTENDANCE_YEAR,
  ECUM_Report_Student.ECUM.ATTEND_CUSTOM.SCHOOL,
  ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_NAME
GO

-- MOBILITY
CREATE PROCEDURE ecum_queries.mobility @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.MOBILITY.SCHOOL_CODE,
  ECUM_Report_Student.ECUM.MOBILITY.ENTRY_DATE,
  ECUM_Report_Student.ECUM.MOBILITY.ENTRY_REASON_CODE,
  ECUM_Report_Student.ECUM.MOBILITY.EXIT_DATE,
  ECUM_Report_Student.ECUM.MOBILITY.EXIT_REASON_CODE
FROM
  ECUM_Report_Student.ECUM.MOBILITY INNER JOIN ECUM_Report_Student.ECUM.STUDENT ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.MOBILITY.STUDENT_NUMBER)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- ELEMGRD
CREATE PROCEDURE ecum_queries.elemgrd @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.SCHOOL_YEAR,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.SCHOOL,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.GRADE_LEVEL,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.RD,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.LA,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.SP,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.FL,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.MT,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.SS,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.SC,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.PE,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.MU,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.CP,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.AR,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.PLACE,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.HW,
  ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.NOGRD
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1 ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.ELEMGRD_CICSTST1.STUDENT_NUMBER)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- FallCLASSHST
CREATE PROCEDURE ecum_queries.fallclasshst @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_FROM_YEAR,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_TO_YEAR,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_GRADE_LEVEL,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER_SORT_CODE,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_LOCATION,
  CASE
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_ALTERNATE_LOCATION = '   '
      THEN  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_COURSE_NAME
      ELSE ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_COURSE_NAME+ltrim(' ('+ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_ALTERNATE_LOCATION+')')
      END HIST_COURSE_NAME,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_COURSE_NUM,
  CASE
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'F' THEN 'FALL'
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'S' THEN 'SPRING'
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'U' THEN 'SUMMER'
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'R' THEN 'CR.RCVY'
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'N' THEN 'NIGHT'
      END HIST_SEMESTER,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEM_GRADE,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_CREDIT_EARNED
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER)
WHERE
  (
   ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
   AND
   ( (ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'F')  OR  ( ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER IN ('N','R','U') AND ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_U_N_R_RPT_PLACEMENT = 1)  )
  )
GO

-- SpringCLASSHST
CREATE PROCEDURE ecum_queries.springclasshst @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_FROM_YEAR,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_TO_YEAR,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_GRADE_LEVEL,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER_SORT_CODE,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_LOCATION,
  CASE
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_ALTERNATE_LOCATION = '   '
      THEN  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_COURSE_NAME
      ELSE ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_COURSE_NAME+ltrim(' ('+ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_ALTERNATE_LOCATION+')')
      END HIST_COURSE_NAME,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_COURSE_NUM,
  CASE
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'F' THEN 'FALL'
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'S' THEN 'SPRING'
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'U' THEN 'SUMMER'
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'R' THEN 'CR.RCVY'
      WHEN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'N' THEN 'NIGHT'
      END HIST_SEMESTER,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEM_GRADE,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_CREDIT_EARNED
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER)
WHERE
  (
   ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
   AND
   ( (ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'S')  OR  ( ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER IN ('N','R','U') AND ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_U_N_R_RPT_PLACEMENT = 2)  )
  )
GO

-- ECUM
CREATE PROCEDURE ecum_queries.ecum @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.BIRTHPLACE,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.BIRTH_CERT_NO,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.BIRTH_OTHER,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.FATHER,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.MOTHER,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.CUSTODY_REL,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.CUST_AFFIDAV,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.COURT_ORDER,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.CUST_DATE,
  ECUM_Report_Student.ECUM.SRECUM_CICSTST1.MOTHER_MAIDEN
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.SRECUM_CICSTST1 ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.SRECUM_CICSTST1.STUDENT_NUMBER)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- BLDG
CREATE PROCEDURE ecum_queries.bldg @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER,
  Alias_STUDENT_ECUM_BUILDING_MASTER.BLDG_NAME,
  Alias_STUDENT_ECUM_BUILDING_MASTER.BLDG_MAILING_NAME,
  Alias_STUDENT_ECUM_BUILDING_MASTER.BLDG_ST_ADDRESS,
  Alias_STUDENT_ECUM_BUILDING_MASTER.BLDG_CITY_STATE,
  Alias_STUDENT_ECUM_BUILDING_MASTER.BLDG_ZIP_CODE,
  Alias_STUDENT_ECUM_BUILDING_MASTER.BLDG_AREA_CODE,
  Alias_STUDENT_ECUM_BUILDING_MASTER.BLDG_TELEPHONE
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.BUILDING_MASTER  Alias_STUDENT_ECUM_BUILDING_MASTER ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_CURR_SCH=Alias_STUDENT_ECUM_BUILDING_MASTER.BLDG_KEY)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- MISC
CREATE PROCEDURE ecum_queries.misc @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.SCMISC_CICSTST1.RANK_STUD,
  ECUM_Report_Student.ECUM.SCMISC_CICSTST1.RANK_CLASS,
  ECUM_Report_Student.ECUM.SCMISC_CICSTST1.GRADUATION_DATE,
  CASE WHEN ECUM_Report_Student.ECUM.SCMISC_CICSTST1.OKLA_SCHOLARS = 'Y' THEN '** Oklahoma Academic Scholar' ELSE '  ' END OKLA_SCHOLARS
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.SCMISC_CICSTST1 ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.SCMISC_CICSTST1.STUDENT_NUMBER)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- DEMO
CREATE PROCEDURE ecum_queries.demo @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.STUDENT_DEMO.PARENT_LNAME,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.PARENT_FNAME,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.PARENT_MI,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.SPARENT_LNAME,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.SPARENT_FNAME,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.SPARENT_MNAME
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.STUDENT_DEMO ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.STUDENT_DEMO.STUDENT_NUMBER)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO

-- Years&Grade
CREATE PROCEDURE ecum_queries.years_grade @student_number INT AS
SELECT
  DISTINCT ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_FROM_YEAR,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_TO_YEAR,
  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_GRADE_LEVEL,
  Table__15.BLDG_NAME FALL_BLDG_NAME,
  Table__16.BLDG_NAME SPRING_BLDG_NAME
FROM
  ECUM_Report_Student.ECUM.STUDENT INNER JOIN ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER)
   LEFT OUTER JOIN (
  SELECT DISTINCT
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER,
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_FROM_YEAR,
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_TO_YEAR,
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_GRADE_LEVEL,
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER,
ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_NAME
FROM ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM
INNER JOIN ECUM_Report_Student.ECUM.BUILDING_MASTER
ON (ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_LOCATION = ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_KEY)
WHERE ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'F'
  )  Table__15 ON (ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER=Table__15.STUDENT_NUMBER  AND  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_FROM_YEAR=Table__15.HIST_FROM_YEAR  AND  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_TO_YEAR=Table__15.HIST_TO_YEAR  AND  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_GRADE_LEVEL=Table__15.HIST_GRADE_LEVEL)
   LEFT OUTER JOIN (
  SELECT DISTINCT
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER,
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_FROM_YEAR,
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_TO_YEAR,
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_GRADE_LEVEL,
ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER,
ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_NAME
FROM ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM
INNER JOIN ECUM_Report_Student.ECUM.BUILDING_MASTER
ON (ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_LOCATION = ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_KEY)
WHERE ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_SEMESTER = 'S'
  )  Table__16 ON (ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.STUDENT_NUMBER=Table__16.STUDENT_NUMBER  AND  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_FROM_YEAR=Table__16.HIST_FROM_YEAR  AND  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_TO_YEAR=Table__16.HIST_TO_YEAR  AND  ECUM_Report_Student.ECUM.CLASS_HISTORY_CUSTOM.HIST_GRADE_LEVEL=Table__16.HIST_GRADE_LEVEL)
WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  =  @student_number
GO


-- Queries lifted from Web Intelligence Report: Student Personal Data Report
--
-- Public Folders / TPS Archive Reports / Accountability
--
-- Title:       Student Personal Data Report
-- ID, CUID:
-- File Name:
-- Description:
--

-- Student Personal Data (spd)
CREATE PROCEDURE ecum_queries.student_personal_data_report @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER,
  rtrim(ECUM_Report_Student.ECUM.STUDENT.STUDENT_LNAME)+', '+rtrim(ECUM_Report_Student.ECUM.STUDENT.STUDENT_FNAME)+' '+rtrim(ECUM_Report_Student.ECUM.STUDENT.STUDENT_MI),
  ECUM_Report_Student.ECUM.STUDENT.GOESBYNAME,
  rtrim(cast(ECUM_Report_Student.ECUM.STUDENT.STUDENT_HOUSE_NO as varchar))+' '+rtrim(ECUM_Report_Student.ECUM.STUDENT.STUDENT_DIRECTION)+' '+rtrim(ECUM_Report_Student.ECUM.STUDENT.STUDENT_STREET)+' '+rtrim(ECUM_Report_Student.ECUM.STUDENT.STUDENT_APT_NO)+' '+rtrim(ECUM_Report_Student.ECUM.STUDENT.STUDENT_LOT_NO)+' '+rtrim(cast(ECUM_Report_Student.ECUM.STUDENT.STUDENT_ZIP1 as varchar)),
  CASE WHEN substring(cast(ECUM_Report_Student.ECUM.STUDENT.STUDENT_PHONE as varchar),1,1) = '0' THEN 'Unknown'
	WHEN  substring(cast(ECUM_Report_Student.ECUM.STUDENT.STUDENT_PHONE as varchar),1,3) = '918' THEN '(918) '+substring(cast(ECUM_Report_Student.ECUM.STUDENT.STUDENT_PHONE as varchar),4,3)+'-'+substring(cast(ECUM_Report_Student.ECUM.STUDENT.STUDENT_PHONE as varchar),7,4)
ELSE '(918) '+substring(cast(ECUM_Report_Student.ECUM.STUDENT.STUDENT_PHONE as varchar),1,3)+'-'+substring(cast(ECUM_Report_Student.ECUM.STUDENT.STUDENT_PHONE as varchar),4,4)
 END,
  CASE when ECUM_Report_Student.ECUM.STUDENT.STUDENT_STATUS = 'A' then 'Active'  when ECUM_Report_Student.ECUM.STUDENT.STUDENT_STATUS = 'I' then 'Inactive' else 'Unknown' END,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_CURR_SCH,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_ENTRY_DATE,
  CASE  WHEN ECUM_Report_Student.ECUM.SCMISC_CICSTST1.CURR_TRANS_CD = '  ' THEN ECUM_Report_Student.ECUM.SCMISC_CICSTST1.ENTRY_REASON ELSE ECUM_Report_Student.ECUM.SCMISC_CICSTST1.ENTRY_REASON+'-'+ECUM_Report_Student.ECUM.SCMISC_CICSTST1.CURR_TRANS_CD END

,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_BIRTHDATE,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_GRADE,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_SEX,
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_RACE,
  ECUM_Report_Student.ECUM.SCMISC_CICSTST1.HEALTH_CD
FROM
  ECUM_Report_Student.ECUM.SCMISC_CICSTST1 RIGHT OUTER JOIN ECUM_Report_Student.ECUM.STUDENT ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.SCMISC_CICSTST1.STUDENT_NUMBER)

WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  = @student_number
GO

-- Student Personal Data (spd) - Mobility
CREATE PROCEDURE ecum_queries.spd_mobility @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.MOBILITY.STUDENT_NUMBER,
  ECUM_Report_Student.ECUM.MOBILITY.SCHOOL_CODE,
  ECUM_Report_Student.ECUM.MOBILITY.ENTRY_DATE,
  CASE  WHEN ECUM_Report_Student.ECUM.MOBILITY.TRANSFER_CODE = '  ' THEN ECUM_Report_Student.ECUM.MOBILITY.ENTRY_REASON_CODE ELSE ECUM_Report_Student.ECUM.MOBILITY.ENTRY_REASON_CODE+'-'+ECUM_Report_Student.ECUM.MOBILITY.TRANSFER_CODE END,
  ECUM_Report_Student.ECUM.MOBILITY.EXIT_DATE,
  ECUM_Report_Student.ECUM.MOBILITY.EXIT_REASON_CODE,
  ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_NAME
FROM
  ECUM_Report_Student.ECUM.BUILDING_MASTER RIGHT OUTER JOIN ECUM_Report_Student.ECUM.MOBILITY ON (ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_KEY=ECUM_Report_Student.ECUM.MOBILITY.SCHOOL_CODE)
   RIGHT OUTER JOIN ECUM_Report_Student.ECUM.STUDENT ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.MOBILITY.STUDENT_NUMBER)

WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  = @student_number
GO

-- Student Personal Data (spd) - Immunizations
CREATE PROCEDURE ecum_queries.spd_immunizations @student_number INT AS
SELECT
  MFLegacy_Student.TSTU_Yr0809.HEALTH.IMMUNIZATION_TYPE,
  MFLegacy_Student.TSTU_Yr0809.HEALTH.FIRST_DATE,
  MFLegacy_Student.TSTU_Yr0809.HEALTH.SECOND_DATE,
  MFLegacy_Student.TSTU_Yr0809.HEALTH.THIRD_DATE,
  MFLegacy_Student.TSTU_Yr0809.HEALTH.FOURTH_DATE,
  MFLegacy_Student.TSTU_Yr0809.HEALTH.FIFTH_DATE,
  MFLegacy_Student.TSTU_Yr0809.HEALTH.SIXTH_DATE,
  MFLegacy_Student.TSTU_Yr0809.HEALTH.CERTIFIED_BY,
  ECUM_Report_Student.ECUM.STUDENT.IMMUN_STATUS
FROM
  MFLegacy_Student.TSTU_Yr0809.HEALTH RIGHT OUTER JOIN ECUM_Report_Student.ECUM.STUDENT ON (MFLegacy_Student.TSTU_Yr0809.HEALTH.STUDID=ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER)

WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  = @student_number
GO

-- Student Personal Data - Special Ed (Active)
CREATE PROCEDURE ecum_queries.spd_special_ed_active @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_PREFIX+ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_NUMBER,
  ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_PROG_DESIGN,
  ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_ENTRY_DATE
FROM
  ECUM_Report_Student.ECUM.SPED_CICSTST1 RIGHT OUTER JOIN ECUM_Report_Student.ECUM.STUDENT ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.SPED_CICSTST1.STUDENT_NUMBER)

WHERE
  (
   ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  = @student_number
   AND
   ( ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_EXIT_DATE is null  )
  )
GO

-- Student Personal Data (spd) - Special Ed (Inactive)
CREATE PROCEDURE ecum_queries.spd_special_ed_inactive @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_PREFIX+ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_NUMBER,
  ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_PROG_DESIGN,
  ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_ENTRY_DATE,
  ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_EXIT_DATE
FROM
  ECUM_Report_Student.ECUM.SPED_CICSTST1 RIGHT OUTER JOIN ECUM_Report_Student.ECUM.STUDENT ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.SPED_CICSTST1.STUDENT_NUMBER)

WHERE
  (
   ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  = @student_number
   AND
   ( ECUM_Report_Student.ECUM.SPED_CICSTST1.SPEC_EXIT_DATE is not null  )
  )
GO

-- Student Personal Data (spd) - Suspensions
CREATE PROCEDURE ecum_queries.spd_suspensions @student_number INT AS
SELECT
  MFLegacy_Student.TSTU_Yr0809.SUSPEND.SCHOOL,
  Table__12."Suspended School",
  CASE WHEN MFLegacy_Student.TSTU_Yr0809.SUSPEND.NOTIFICATION = '1' THEN 'Phone'
          WHEN MFLegacy_Student.TSTU_Yr0809.SUSPEND.NOTIFICATION = '2' THEN 'Written'
          ELSE null END,
  MFLegacy_Student.TSTU_Yr0809.SUSPEND.START_DATE,
  MFLegacy_Student.TSTU_Yr0809.SUSPEND.END_DATE,
  MFLegacy_Student.TSTU_Yr0809.SUSPEND.NUMBER_DAYS,
  MFLegacy_Student.TSTU_Yr0809.SUSPEND_REASON_CODES.REASON_DESCRIPTION,
  CASE when MFLegacy_Student.TSTU_Yr0809.SUSPEND.COMMENT_LINE_1 = 'PLACEMENT' then 'Placement'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.COMMENT_LINE_1 = 'PARENT OPTION' then 'Parent Option'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.COMMENT_LINE_1 = 'HOMEBASED' then 'Home Based'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '01' then 'Class Room/Library'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '02' then 'Halls'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '03' then 'Restroom'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '04' then 'Cafeteria'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '05' then 'Outside Building'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '06' then 'School Bus'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '07' then 'Parking Lot'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '08' then 'Off Campus'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '09' then 'Gym'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '10' then 'Auditorium'
	 when MFLegacy_Student.TSTU_Yr0809.SUSPEND.LOCATION = '11' then 'Other'
ELSE null
END
FROM
  ECUM_Report_Student.ECUM.STUDENT LEFT OUTER JOIN MFLegacy_Student.TSTU_Yr0809.SUSPEND ON (MFLegacy_Student.TSTU_Yr0809.SUSPEND.STUDID=ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER)
   LEFT OUTER JOIN MFLegacy_Student.TSTU_Yr0809.SUSPEND_REASON_CODES ON (MFLegacy_Student.TSTU_Yr0809.SUSPEND.REASON=MFLegacy_Student.TSTU_Yr0809.SUSPEND_REASON_CODES.REASON)
   LEFT OUTER JOIN (
  select DISTINCT ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_KEY as 'BLDG_KEY', ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_NAME as 'Suspended School'
from ECUM_Report_Student.ECUM.BUILDING_MASTER
inner join MFLegacy_Student.TSTU_Yr0809.SUSPEND
on ECUM_Report_Student.ECUM.BUILDING_MASTER.BLDG_KEY=MFLegacy_Student.TSTU_Yr0809.SUSPEND.SCHOOL
  )  Table__12 ON (MFLegacy_Student.TSTU_Yr0809.SUSPEND.SCHOOL=Table__12.BLDG_KEY)

WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  = @student_number
GO

-- Student Personal Data - Demo
CREATE PROCEDURE ecum_queries.spd_demo @student_number INT AS
SELECT
  ECUM_Report_Student.ECUM.STUDENT_DEMO.PARENT_LNAME,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.PARENT_FNAME,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.PARENT_MI,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.SPARENT_LNAME,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.SPARENT_FNAME,
  ECUM_Report_Student.ECUM.STUDENT_DEMO.SPARENT_MNAME
FROM
  ECUM_Report_Student.ECUM.STUDENT_DEMO RIGHT OUTER JOIN ECUM_Report_Student.ECUM.STUDENT ON (ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER=ECUM_Report_Student.ECUM.STUDENT_DEMO.STUDENT_NUMBER)

WHERE
  ECUM_Report_Student.ECUM.STUDENT.STUDENT_NUMBER  = @student_number
GO
